# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FTC-Scouting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FTC-Scouting

  target 'FTC-ScoutingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FTC-ScoutingUITests' do
    # Pods for testing
  end

end

target 'NeocraticStickers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NeocraticStickers
pod 'IQKeyboardManagerSwift'
end
